# Generated by Django 5.2.10 on 2026-07-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPGROUP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAutomation',
        ),
    ]
