# Generated by Django 5.2.10 on 2026-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APPGROUP', '0002_delete_homeautomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAutomation',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=100)),
                ('House', models.CharField(max_length=120)),
                ('room', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('api_url', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_automation',
                'ordering': ['room', 'device_name', 'display_order'],
                'unique_together': {('room', 'device_name', 'action')},
            },
        ),
    ]
