# Generated by Django 5.2.10 on 2026-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPGROUP', '0004_userhousemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.IntegerField()),
                ('place_name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField()),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('map_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'location_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
