# Generated by Django 5.2.9 on 2025-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_bank', models.CharField(max_length=150)),
                ('receiver_bank', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='DEM_transac_timesta_ea82d4_idx'), models.Index(fields=['user'], name='DEM_transac_user_0a5954_idx'), models.Index(fields=['category'], name='DEM_transac_categor_81a225_idx'), models.Index(fields=['sub_category'], name='DEM_transac_sub_cat_d9065b_idx'), models.Index(fields=['status'], name='DEM_transac_status_c0845c_idx')],
            },
        ),
    ]
