# Generated by Django 5.2.9 on 2025-12-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expense_category',
                'ordering': ['category', 'sub_category'],
                'unique_together': {('category', 'sub_category')},
            },
        ),
    ]
