# Generated by Django 5.2.9 on 2025-12-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0003_expensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='notes',
            field=models.TextField(blank=True, help_text='Semantic hints / keywords for auto categorisation'),
        ),
    ]
