# Generated by Django 5.2.9 on 2026-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0004_expensecategory_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('month', models.DateField(db_index=True, help_text='Store first day of month (YYYY-MM-01)')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expense_category_plan',
                'ordering': ['category'],
                'unique_together': {('user', 'month', 'category')},
            },
        ),
    ]
