# Generated by Django 5.2.9 on 2026-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0005_expensecategoryplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_auto_cat',
            field=models.IntegerField(default=0),
        ),
    ]
