# Generated by Django 5.2.9 on 2026-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0006_transaction_is_auto_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
