# Generated by Django 5.2.10 on 2026-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(db_index=True, default='DEFAULT', max_length=100)),
                ('category', models.CharField(db_index=True, help_text='Top level category e.g. Bank & Money', max_length=100)),
                ('sub_category', models.CharField(help_text='Sub category e.g. Credit Card', max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('status', models.IntegerField(default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sub_category'],
                'unique_together': {('family', 'category', 'sub_category')},
            },
        ),
    ]
