# Generated by Django 5.2.10 on 2026-01-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docma_MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(db_index=True, default='DEFAULT', help_text='Family to which this document belongs', max_length=100)),
                ('refnumber', models.CharField(blank=True, db_index=True, help_text='External or document reference number (Aadhaar, Policy No, etc.)', max_length=200, null=True, unique=True)),
                ('holder', models.CharField(help_text='Person in the family who owns this document', max_length=200)),
                ('category', models.CharField(help_text='Top-level category (Bank & Money, Education, etc.)', max_length=100)),
                ('sub_category', models.CharField(help_text='Specific document type (Credit Card, Aadhaar, etc.)', max_length=100)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted OCR text for AI search and understanding', null=True)),
                ('price', models.IntegerField(default=0, help_text='Cost paid for the document (if applicable)')),
                ('value', models.IntegerField(default=0, help_text='Assessed or insured value (if applicable)')),
                ('start_date', models.DateField(blank=True, help_text='Start or issue date (if applicable)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End or expiry date (if applicable)', null=True)),
                ('status', models.IntegerField(default=1, help_text='1 = Active, 0 = Inactive, 2 = Archived')),
                ('remarks', models.CharField(blank=True, help_text='Additional notes', max_length=300)),
                ('updated_by', models.CharField(help_text='User who last updated this document', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated timestamp')),
            ],
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='icon',
            field=models.ImageField(blank=True, default='MEDIA/DOCMA/MasterCategoryIcons/default.png', null=True, upload_to='MEDIA/DOCMA/DOCMA/MasterCategoryIcons/'),
        ),
        migrations.CreateModel(
            name='DocmaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded document file (image or PDF)', upload_to='docma/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DOCMA.docma_metadata')),
            ],
        ),
    ]
