# Generated by Django 5.2.10 on 2026-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0002_docma_metadata_alter_categorymaster_icon_docmafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docmafile',
            name='file',
        ),
        migrations.AddField(
            model_name='docmafile',
            name='file_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='docmafile',
            name='file_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='docmafile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docmafile',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='docmafile',
            name='file_url',
            field=models.TextField(default=''),
        ),
    ]
