# Generated by Django 5.2.10 on 2026-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0003_remove_docmafile_file_docmafile_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaster',
            name='icon',
            field=models.ImageField(blank=True, default='staticfiles/DOCMA/MasterCategoryIcons/default.png', null=True, upload_to='staticfiles/DOCMA/MasterCategoryIcons/'),
        ),
    ]
