# Generated by Django 5.2.10 on 2026-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0004_alter_categorymaster_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaster',
            name='icon',
            field=models.ImageField(blank=True, default='DOCMA/MasterCategoryIcons/default.png', null=True, upload_to='DOCMA/MasterCategoryIcons/'),
        ),
    ]
