# Generated by Django 5.2.10 on 2026-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('food_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('meal_type', models.CharField(blank=True, max_length=20)),
                ('estimated_calories', models.FloatField(blank=True, null=True)),
                ('estimated_protein', models.FloatField(blank=True, null=True)),
                ('estimated_carbs', models.FloatField(blank=True, null=True)),
                ('estimated_fats', models.FloatField(blank=True, null=True)),
                ('estimated_fiber', models.FloatField(blank=True, null=True)),
                ('estimated_sugar', models.FloatField(blank=True, null=True)),
                ('estimated_sodium', models.FloatField(blank=True, null=True)),
                ('x_field', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='MEDTRAC_mea_user_567b94_idx')],
            },
        ),
    ]
