# Generated by Django 5.2.10 on 2026-03-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0002_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='ai_analytics_req',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
