# Generated by Django 5.2.10 on 2026-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0003_meallog_ai_analytics_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='id',
        ),
        migrations.AddField(
            model_name='meallog',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
