# Generated by Django 5.2.10 on 2026-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0004_remove_meallog_id_meallog_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='is_nonveg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
