# Generated by Django 5.2.10 on 2026-08-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0006_medicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEventLog',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('medical_event', models.CharField(max_length=255)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['user_name', 'start'], name='MEDTRAC_med_user_na_ec0f71_idx')],
            },
        ),
    ]
