# Generated by Django 5.2.10 on 2026-08-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0007_medicaleventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAnalysisMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('health_rating', models.CharField(max_length=50)),
                ('health_score', models.IntegerField()),
                ('health_recommendation', models.TextField()),
                ('top_problems', models.TextField(blank=True)),
                ('top_positive_patterns', models.TextField(blank=True)),
                ('no_of_meals', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=20)),
                ('timing_status', models.IntegerField()),
                ('timing_metrics', models.CharField(blank=True, max_length=100, null=True)),
                ('timing_ai_remarks', models.TextField()),
                ('quantity_status', models.IntegerField()),
                ('quantity_ai_remarks', models.TextField()),
                ('portion_status', models.IntegerField()),
                ('portion_ai_remarks', models.TextField()),
                ('nutrition_status', models.IntegerField()),
                ('nutrition_ai_remarks', models.TextField()),
                ('overall_status', models.IntegerField()),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('overall_ai_remarks', models.TextField()),
                ('add_recommendations', models.TextField(blank=True)),
                ('avoid_recommendations', models.TextField(blank=True)),
                ('analysis_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_analyses', to='MEDTRAC.healthanalysismeta')),
            ],
        ),
    ]
